Push-Location

$armaToolsFolder = "C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Tools"


$pboFileName = Get-Content -Path "PBO_FILE_NAME.txt" -TotalCount 1
"Read PBO file name: $pboFileName"


$modBuildPath = "_build\@$pboFileName"


"Ensure directories.."
forEach ($folder in (Get-Childitem -directory -name "_build")) {
    Remove-Item "_build\$folder" -Recurse -Force
}
New-Item $modBuildPath -ItemType Directory -Force > $null
New-Item "$modBuildPath\addons" -ItemType Directory -Force > $null


"Copy extra files.."
Copy-Item "Arma mod\mod.cpp" $modBuildPath > $null


"Copy addons.."
Copy-Item "Arma mod\addons\addon" "$modBuildPath\addons" -Recurse > $null


"Generate PBO_FILE_NAME.hpp"
Remove-Item "$modBuildPath\addons\addon\PBO_FILE_NAME.hpp"
"// Auto generated file`n#define PBO_FILE_NAME $pboFileName" >> "$modBuildPath\addons\addon\PBO_FILE_NAME.hpp"


"Generate loadout init file.."
$initLoadoutsSQF = "#include `"common.hpp`"`n// This file is autogenerated`n"
$loadoutFiles = Get-Childitem "$modBuildPath\addons\addon\loadouts"
foreach ($file in $loadoutfiles) {
    #$ext = $file.Extension
    $loadoutName = $file.baseName 
    $fileName = $file.Name
    "  Found loadout: $loadoutName $fileName"

    $initLoadoutsSQF += "[`"$loadoutName`", `PATH_TO_FILE(loadouts\$fileName)] call t_fnc_addLoadout;`n"
}
$initLoadoutsSQF | Out-File -FilePath "$modBuildPath\addons\addon\initLoadouts.sqf" -NoNewline -Encoding UTF8


"Rename folder.."
Rename-Item "$modBuildPath\addons\addon" "$pboFileName"

"Build pbos..."

& "$armaToolsFolder\AddonBuilder\AddonBuilder.exe" "$PSScriptRoot\$modBuildPath\addons\$pboFileName" "$PSScriptRoot\$modBuildPath\addons" -packonly -prefix="$pboFileName"


"Delete temp folder.."
Remove-Item "$modBuildPath\addons\$pboFileName" -Recurse -Force

Pop-Location

"`n`nDone!"

pause